// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLQb63ZasZhj7eFng7qsg_qc4CTamYwUE',
    appId: '1:1058011763803:web:761915e20697b16a959b7e',
    messagingSenderId: '1058011763803',
    projectId: 'heza-chat',
    authDomain: 'heza-chat.firebaseapp.com',
    storageBucket: 'heza-chat.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA3QSAqt6Ikvon0yTD7qz6Xt-t4jsE0lg',
    appId: '1:1058011763803:android:b6f1bbc49fc32883959b7e',
    messagingSenderId: '1058011763803',
    projectId: 'heza-chat',
    storageBucket: 'heza-chat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPOyIl3ghN55NEn8Ce1pU1lgJVWpdAmu4',
    appId: '1:1058011763803:ios:451f42a7229c0562959b7e',
    messagingSenderId: '1058011763803',
    projectId: 'heza-chat',
    storageBucket: 'heza-chat.appspot.com',
    iosClientId: '1058011763803-9chp072bntd4gsupevohhd9d7e0tfcuc.apps.googleusercontent.com',
    iosBundleId: 'com.example.hezaChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPOyIl3ghN55NEn8Ce1pU1lgJVWpdAmu4',
    appId: '1:1058011763803:ios:c69d8fa2ee904795959b7e',
    messagingSenderId: '1058011763803',
    projectId: 'heza-chat',
    storageBucket: 'heza-chat.appspot.com',
    iosClientId: '1058011763803-uu708euuokrkv04km0kepb6eht9u59e5.apps.googleusercontent.com',
    iosBundleId: 'com.example.hezaChat.RunnerTests',
  );
}
